### ISSUE TITLE
请求api返回状态码不一致

### ISSUE THREAD

**Issue by cy920820** [zce/douban-api-docs#1]
同样都是调用 https://api.douban.com/v2/movie/in_theaters 这个接口
浏览器下返回正常200 :
![image](https://user-images.githubusercontent.com/21211512/53855427-89f59580-4008-11e9-82fb-12729fbf0061.png)

但在wx开发者工具中返回403（未开启合法域名校验）：
![image](https://user-images.githubusercontent.com/21211512/53855440-97ab1b00-4008-11e9-9d9a-e04e688d5db8.png)

**Comment by zce** [comment]
https://github.com/zce/douban-api-proxy
