### ISSUE TITLE
关于项目和 Issue 的说明

### ISSUE THREAD

**Issue by zce** [zce/douban-api-docs#28]
最近太多人因为豆瓣接口的问题找我，确实很苦恼，在此重申一遍：

1. 我不是官方，官方接口出现不稳定及其他问题，我解决不了！
2. 我只是因为很多人找不到官方文档，基于历史归档重新整理了一份！
3. 为了尽可能接近官方文档的原始内容，我并没有对文档的正确性进行校对！换而言之，原来的官方文档什么样，这里就是什么样！
4. 至于我搭建的代理服务，同样也是这个道理：「源头」有问题，「中间商」无法根治！

考虑到确实很多人没有基础，所以产生这样的问题情有可原。但是我希望大家不要急功近利，戒骄戒躁，补充点基础。虽然在你们平时看起来这很浪费时间，但是你们这样就不怕出现问题从而浪费别人的时间么～

**Comment by zhuige** [comment]
为什么我在浏览器请求你那个代理地址还是会报403错，难道在小程序或者app里面不会报错吗

**Comment by zhuige** [comment]
作者能不能做一下跨域的问题，访问你的地址服务器不允许跨域

**Comment by L-doubleJ** [comment]
求回复

**Comment by zce** [comment]
> 作者能不能做一下跨域的问题，访问你的地址服务器不允许跨域

可以考虑，请不要把这里当作贴吧来用，还有希望能在相应的仓库提 Issue，谢谢

**Comment by zce** [comment]
> 作者能不能做一下跨域的问题，访问你的地址服务器不允许跨域

@L-doubleJ https://github.com/zce/douban-api-proxy/issues/33 代理服务现已支持 CORS。

**Comment by ishowman** [comment]
请问有官方原文档的备份吗

**Comment by zce** [comment]
[接口](https://github.com/zce/douban-api-proxy) 是代理到豆瓣的官方 API，代理过程只是修改了 Referer（为了解决屏蔽小程序问题）、添加额外的 apiKey（为了部分特殊接口的访问）、支持 CORS，其余的都跟官方 API 没有区别。

[文档](https://github.com/zce/douban-api-docs) 是我从之前的 [网页历史博物馆](https://archive.org) 中整理出来的豆瓣 API 官方文档，只是修正了部分格式和明显的字面错误。

也就是说，对于官方 API 本身的问题，我并没有特殊处理（很多事情无能为力），其中包括（不限于）：

- 搜索接口无法调用问题
- 接口实际调用与文档不一致
- 接口限额问题，目前每个代理地址的限额是（10000/h）

特此说明。

**Comment by zce** [comment]
> 请问有官方原文档的备份吗

没有，所有资料手工整理

**Comment by LynnDT** [comment]
你好，您的douban.uieee.com已经无法访问了，请问是SSL证书过期了还是其它问题呢？

**Comment by zce** [comment]
> 你好，您的douban.uieee.com已经无法访问了，请问是SSL证书过期了还是其它问题呢？

原本阿里云的服务器到期，暂时没有合适的服务器

**Comment by zce** [comment]
douban.uieee.com 已经迁移到 ZEIT Now 上，有问题随时反馈

**Comment by sukai-cheng** [comment]
douban.uieee.com已经无法访问了

**Comment by zce** [comment]
应豆瓣官方要求，该服务已经下架
